//codes by ashishvz//

using System;

class Program
{
    static void Main()
    {
        string stra,newstring,after;
            Console.WriteLine("Enter the Sentence to encrypte");
            stra = Console.ReadLine();
            char[] tempstr = stra.ToCharArray();
           
           
            for(int i=0;i<tempstr.Length;i++)
            {
                if(char.IsLower(tempstr[i]))
                {
                    if(tempstr[i].Equals('a'))
                    {
                        tempstr[i]='1';
                    }
                    if(tempstr[i].Equals('b'))
                    {
                        tempstr[i]='R';
                    }
                    if(tempstr[i].Equals('c'))
                    {
                        tempstr[i]='t';
                    }
                    if(tempstr[i].Equals('d'))
                    {
                        tempstr[i]='Z';
                    }
                    if(tempstr[i].Equals('e'))
                    {
                        tempstr[i]='7';
                    }
                    if(tempstr[i].Equals('f'))
                    {
                        tempstr[i]='W';
                    }
                    if(tempstr[i].Equals('g'))
                    {
                        tempstr[i]='l';
                    }
                    if(tempstr[i].Equals('h'))
                    {
                        tempstr[i]='u';
                    }
                    if(tempstr[i].Equals('i'))
                    {
                        tempstr[i]='D';
                    }
                    if(tempstr[i].Equals('j'))
                    {
                        tempstr[i]='P';
                    }
                    if(tempstr[i].Equals('k'))
                    {
                        tempstr[i]='V';
                    }
                    if(tempstr[i].Equals('l'))
                    {
                        tempstr[i]='4';
                    }
                    if(tempstr[i].Equals('m'))
                    {
                        tempstr[i]='Q';
                    }
                    if(tempstr[i].Equals('n'))
                    {
                        tempstr[i]='T';
                    }
                    if(tempstr[i].Equals('o'))
                    {
                        tempstr[i]='F';
                    }
                    if(tempstr[i].Equals('p'))
                    {
                        tempstr[i]='M';
                    }
                    if(tempstr[i].Equals('q'))
                    {
                        tempstr[i]='G';
                    }
                    if(tempstr[i].Equals('r'))
                    {
                        tempstr[i]='x';
                    }
                    if(tempstr[i].Equals('s'))
                    {
                        tempstr[i]='I';
                    }
                    if(tempstr[i].Equals('t'))
                    {
                        tempstr[i]='k';
                    }
                    if(tempstr[i].Equals('u'))
                    {
                        tempstr[i]='H';
                    }
                    if(tempstr[i].Equals('v'))
                    {
                        tempstr[i]='r';
                    }
                    if(tempstr[i].Equals('w'))
                    {
                        tempstr[i]='S';
                    }
                    if(tempstr[i].Equals('x'))
                    {
                        tempstr[i]='U';
                    }
                    if(tempstr[i].Equals('y'))
                    {
                        tempstr[i]='V';
                    }
                    if(tempstr[i].Equals('z'))
                    {
                        tempstr[i]='m';
                    }
                }
                else
                {
                     if(tempstr[i].Equals('A'))
                    {
                        tempstr[i]='n';
                    }
                    if(tempstr[i].Equals('B'))
                    {
                        tempstr[i]='e';
                    }
                    if(tempstr[i].Equals('C'))
                    {
                        tempstr[i]='i';
                    }
                    if(tempstr[i].Equals('D'))
                    {
                        tempstr[i]='6';
                    }
                    if(tempstr[i].Equals('E'))
                    {
                        tempstr[i]='A';
                    }
                    if(tempstr[i].Equals('F'))
                    {
                        tempstr[i]='5';
                    }
                    if(tempstr[i].Equals('G'))
                    {
                        tempstr[i]='N';
                    }
                    if(tempstr[i].Equals('H'))
                    {
                        tempstr[i]='E';
                    }
                    if(tempstr[i].Equals('I'))
                    {
                        tempstr[i]='C';
                    }
                    if(tempstr[i].Equals('J'))
                    {
                        tempstr[i]='Y';
                    }
                    if(tempstr[i].Equals('K'))
                    {
                        tempstr[i]='3';
                    }
                    if(tempstr[i].Equals('L'))
                    {
                        tempstr[i]='J';
                    }
                    if(tempstr[i].Equals('M'))
                    {
                        tempstr[i]='j';
                    }
                    if(tempstr[i].Equals('N'))
                    {
                        tempstr[i]='W';
                    }
                    if(tempstr[i].Equals('O'))
                    {
                        tempstr[i]='B';
                    }
                    if(tempstr[i].Equals('P'))
                    {
                        tempstr[i]='a';
                    }
                    if(tempstr[i].Equals('Q'))
                    {
                        tempstr[i]='o';
                    }
                    if(tempstr[i].Equals('R'))
                    {
                        tempstr[i]='z';
                    }
                    if(tempstr[i].Equals('S'))
                    {
                        tempstr[i]='0';
                    }
                    if(tempstr[i].Equals('T'))
                    {
                        tempstr[i]='c';
                    }
                    if(tempstr[i].Equals('U'))
                    {
                        tempstr[i]='L';
                    }
                    if(tempstr[i].Equals('V'))
                    {
                        tempstr[i]='g';
                    }
                    if(tempstr[i].Equals('W'))
                    {
                        tempstr[i]='b';
                    }
                    if(tempstr[i].Equals('X'))
                    {
                        tempstr[i]='9';
                    }
                    if(tempstr[i].Equals('Y'))
                    {
                        tempstr[i]='8';
                    }
                    if(tempstr[i].Equals('Z'))
                    {
                        tempstr[i]='2';
                    }
                }
                 if(tempstr[i].Equals('0'))
                    {
                        tempstr[i]='x';
                    }
                 if(tempstr[i].Equals('1'))
                    {
                        tempstr[i]='q';
                    }
                 if(tempstr[i].Equals('2'))
                    {
                        tempstr[i]='K';
                    }
                 if(tempstr[i].Equals('3'))
                    {
                        tempstr[i]='S';
                    }
                 if(tempstr[i].Equals('4'))
                    {
                        tempstr[i]='y';
                    }
                 if(tempstr[i].Equals('5'))
                    {
                        tempstr[i]='f';
                    }
                 if(tempstr[i].Equals('6'))
                    {
                        tempstr[i]='d';
                    }
                if(tempstr[i].Equals('7'))
                    {
                        tempstr[i]='h';
                    }
                 if(tempstr[i].Equals('8'))
                    {
                        tempstr[i]='O';
                    }
                 if(tempstr[i].Equals('9'))
                    {
                        tempstr[i]='p';
                    }
                    
            }
            newstring = new String(tempstr);
            after = newstring.Replace(" ", String.Empty);
            Console.WriteLine("String is="+after);
            Console.ReadLine();
    }
}
